### ISSUE TITLE
Reference to WCode's - "limitations"

### ISSUE THREAD

**Issue by ujLion** [bandrews/verbal-id#7]
Hi Ben, first of all - thanks a lot for referencing my project [WCode](https://wcodes.org) and also building on and improving the wordlist.

I just wanted to clarify that WCode was built with the very clear intention to minimize any ambiguity of communication. The existence of words like "landslide" and any homophones in its wordlist in any early or even current version - would have been a mistake / a temporary oversight - as I had **EXPLICITLY** stated that WCode's words should exclude such compounded words and homophones.

![Word selection criteria - highlighted](https://user-images.githubusercontent.com/2406365/123854016-bc470180-d93b-11eb-8104-2f1512b9a7c2.jpg)

**Comment by bandrews** [comment]
Hi @ujLion - thanks for reaching out, and especially thanks for choosing to share the [WCode word list](https://web.archive.org/web/20210502100723if_/https://wcodes.org/wordlist) in the public domain - it was a great contribution to the community, and I mentioned the project in the notes here specifically because I wanted to thank you for offering that as a resource.

The primary challenge that kept me from adopting the WCode wordlist directly was the "to be replaced" list of 74 words, which contains various items like "death", "cancer", "cannon" and "sword".  Since those are marked as to be replaced, I'm sure future releases of the WCode list will replace and improve on these words, but these inclusions were unacceptable for my purposes as the list currently stands.  I also removed some other words that could have mildly inappropriate or unpleasant connotations in certain settings, like "collar" and "cockroach".

I did already acknowledge the design goals you list here and indicate that I made a design decision to adopt different restrictions than WCode in verbal-id in this note on the project homepage:

> I discarded a few limitations WCodes adopted; most notably, this list permits common compound words that aren't typically hyphenated like 'landscape' and 'moonlight'.

As I'm sure you've encountered too, I found that the pool of short, simple, phonetically unique words to adopt as replacements was surprisingly small, and so I made the decision to include compound words to backfill back up to 1024 options after removals because I was out of other words I found to be suitable that had unique Metaphone codes and that were included in multiple ESL dictionaries.  I made an effort while doing that to choose words that are commonly pronounced without a pause between the two compound word stems, in the hopes that users will not accidentally split them up, but this is definitely an area where our projects diverge.

Since the intent of referencing WCode is to acknowledge your community contributions and thank you for your efforts, I certainly don't want you to be unhappy with the way your project is referenced in the verbal-id documentation.  Would you like me to remove the WCode acknowledgment entirely, or would you like me to reference this issue from the project welcome page as a point of clarification?  I'm happy to do either upon request.

Thanks again for everything you've done, and best of luck with the WCode project!

**Comment by ujLion** [comment]
Oh - my bad, I read your sentence wrong! In the paragraph that you have quoted above - I misinterpreted **this list** as the *WCode list* when you actually meant *VerbalID list*. Thanks again @bandrews for taking out time to address my concern. Even though your sentence is proper, I would request you to make it a little more clear - so that someone else does not repeat my mistake in interpreting it; So instead of "this list" you could say: "the VerbalID list" or place 'VerbalID' in brackets there.

**Comment by ujLion** [comment]
`Existing projects like WCodes have provided a similar idea, but the word list contains homophones and words with negative connotations.

I also wanted the system to be tolerant to minor typos...`

Here I want to stress that - WCode has had these same goals... It is just that I, like you @bandrews , was short of words... And thus have had to keep poor words as a **temporary** arrangement. Thus the limitations are of WCode's *word list* and *NOT* the *WCode* system itself.
When you have time - it would be kind of you to make this distinction in your reference.
I do also acknowledge that you have been more diligent and systematic in improving the words of the list - and have made it much more useful for all.

**Comment by bandrews** [comment]
Thanks, this all makes sense!  I definitely appreciate the feedback, and I agree this needed to be clearer.  I went ahead and made updates to README.md to address them and to make it clearer that the divergence between the two projects is simply based on different design goals.

Please take a look and see what you think;  if you have further feedback, let me know, and otherwise feel free to close the issue if your concerns are resolved.

Cheers!

**Comment by ujLion** [comment]
Just to point out:

> verbal-id aggressively filters words that even have a small chance of being interpreted with negative connotations or potentially offensive meanings when combined with other words.

As mentioned above in point *8* & *9* of WCode's **Word selection criteria** list - I have always wanted to keep the words of WCode as positive as possible in order to avoid any potential negative connotations. Thus discouraged words like pig (I love all animals and insects though - just that not all people can get on to same page right now), and even the **slightest** negative word like "fall". However it may so be that you may find some words to be inappropriate which I might not, and thus VebralID's list could be more aggressive in such filtering.


> verbal-id uses Metaphone phonetic codes to filter the word list for homophones and to match words entered by users, enabling the system to be tolerant to minor typos (e.g. "kiwi" and "keewee" map to the same metaphone code).

I had intended to handle this matter - at input level. i.e. if the user would enter a misspelling - like 'keewee' - it would get auto corrected to 'kiwi' upon decoding.

 \* This is currently not implemented in WCodes though.

> verbal-id incorporates parity bits as a checksum to enable friendly error handling.

WCodes has had this feature since the beginning. It is part of the [executable](https://wcodes.org/user_guide) and demoed in the [video](https://wcodes.org/video).
However this has been an optional feature, in order to keep the code shortest if that is the user's priority.

@bandrews I am happy 🙂 with your response. You may close this issue.
Thanks brother ✊
